### Generated by update script.


{
  version = "5.34.0";
  sha512 = {
    x64 = "2rnj3wcbhdnr053gbmjw8ms6pq44dr6xd29fp1glbzx1kq01w1nypqk9s5alnc76g2d0all0csvvvzvi6fgc42hh9g0jr3z85j2yri7";
    arm64 = "37wivmqdn7wpybqfz1lcxgf9cv0p9nn9zssc3ilmrs5x2m6hddiw09rigzx7i5lp1j6z0rcwb28hganzdnjmk0rci2yh5srmwnnsr6r";
  };
}
