#!/usr/bin/env nix-shell
#! nix-shell -i bash -p curl yq-go

latest_release=$(curl --silent https://updates.signal.org/desktop/latest-mac.yml)
version=$(yq e '.version' - <<< "$latest_release")

dirname=$(dirname "$0")
output_settings="$dirname/settings.nix"

echo Using version "$version"

warning=$'### Generated by update script.\n\n'
printf '%s{\n  version = \"%s\";\n}\n' "$warning" "$version" > $output_settings
