#!/usr/bin/env nix-shell
#! nix-shell -i bash -p curl nix-prefetch jq

branch="emacs-28"
readme=$(curl --silent https://raw.githubusercontent.com/emacs-mirror/emacs/$branch/README)

version=$(grep -Eo '[0-9]+\.[0-9]+\.[0-9]+' <<< $readme)
dirname=$(dirname "$0")

output="$dirname/settings.nix"

warning=$'### Generated by update script.\n\n'
echo -e "${warning}{\n  emacsBranch = \"${branch}\";\n  emacsVersion = \"${version}\";\n}" > $output

echo "Using emacs version $version on branch $branch"
